# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: containerly.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x63ontainerly.proto\x12\x0b\x63ontainerly\"\x1a\n\x07Request\x12\x0f\n\x07message\x18\x01 \x01(\x0c\"\x1b\n\x08Response\x12\x0f\n\x07message\x18\x01 \x01(\x0c\x32\x41\n\x07Runtime\x12\x36\n\x07Service\x12\x14.containerly.Request\x1a\x15.containerly.ResponseB\x0fZ\r.;containerlyb\x06proto3')



_REQUEST = DESCRIPTOR.message_types_by_name['Request']
_RESPONSE = DESCRIPTOR.message_types_by_name['Response']
Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), {
  'DESCRIPTOR' : _REQUEST,
  '__module__' : 'containerly_pb2'
  # @@protoc_insertion_point(class_scope:containerly.Request)
  })
_sym_db.RegisterMessage(Request)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'containerly_pb2'
  # @@protoc_insertion_point(class_scope:containerly.Response)
  })
_sym_db.RegisterMessage(Response)

_RUNTIME = DESCRIPTOR.services_by_name['Runtime']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\r.;containerly'
  _REQUEST._serialized_start=34
  _REQUEST._serialized_end=60
  _RESPONSE._serialized_start=62
  _RESPONSE._serialized_end=89
  _RUNTIME._serialized_start=91
  _RUNTIME._serialized_end=156
# @@protoc_insertion_point(module_scope)
